name: 每日行情更新

on:
  schedule:
    # UTC 01:00 = Asia/Taipei 09:00 (Daily)
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run:
    name: 更新品項價格（每日）
    runs-on: ubuntu-latest
    env:
      SOURCE_VEG_URL: https://amis.afa.gov.tw/veg/VegProdDayTransInfo.aspx
      SOURCE_FRUIT_URL: https://amis.afa.gov.tw/fruit/FruitProdDayTransInfo.aspx
      SOURCE_VEG_SELECTOR_URL: https://amis.afa.gov.tw/Selector/VegProductSelector.aspx?textField=ctl00_contentPlaceHolder_txtProduct&valueField=ctl00_contentPlaceHolder_hfldProductNo&productTypeField=ctl00_contentPlaceHolder_hfldProductType
      SOURCE_FRUIT_SELECTOR_URL: https://amis.afa.gov.tw/Selector/FruitProductSelector.aspx?textField=ctl00_contentPlaceHolder_txtProduct&valueField=ctl00_contentPlaceHolder_hfldProductNo&productTypeField=ctl00_contentPlaceHolder_hfldProductType
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID_DAILY }}
      GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT: ${{ secrets.GOOGLE_SERVICE_ACCOUN